### PR TITLE
Throw exception if docker files missing

### PR DESCRIPTION
**Pull request by AydinHassan**

### CODE REVIEW

**Comment by mikeymike** [comment]
do think it's worth checking all the files are there ?

**Comment by mikeymike** [comment]
e.g. 
```
app.php.dockerfile
docker-compose.yml
docker-compose.dev.yml
.docker/local.env
```

**Comment by AydinHassan** [comment]
@mikeymike Maybe - but this is more important. Get this error a lot when running in a different directory when I forgot I moved.

**Comment by mikeymike** [comment]
tbh if they don't exist but these files do the project is pretty screwed anyway 😂

**Review by mikeymike — APPROVED** [review]

**Pull request merged**
